apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: loiwmakkm-go 
  janus-idp.io/tekton: loiwmakkm-go
  backstage.io/kubernetes-id: loiwmakkm-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: loiwmakkm-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  